server:
  port: 8080
spring:
  application:
    name: DOCTOR-SERVICE
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/i_med_doctor_service
    password: 2901
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
